name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:    
    - name: Checkout code - Toma lo que esta en el repositorio
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Fin del login"

    - name: Build Docker Image
      run: |
        docker build -t fabiankoliren/docker-graphql:0.0.2 .
        docker build -t fabiankoliren/docker-graphql:latest .

    - name: Push Docker Image
      run: |
        docker push fabiankoliren/docker-graphql:0.0.2
        docker push fabiankoliren/docker-graphql:latest

      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
